# Generated by Django 5.2.4 on 2025-08-05 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Demande de réservation', 'verbose_name_plural': 'Demandes de réservation'},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('edinar', 'Carte e-dinar'), ('rib', 'Virement RIB'), ('mobile_money', 'Mobile Money'), ('other', 'Autre')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente de vérification'), ('verified', 'Payé et vérifié'), ('rejected', 'Paiement invalide')], default='pending', max_length=15)),
                ('proof', models.ImageField(help_text='Reçu de paiement', upload_to='payments/')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Informations complémentaires')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='residents.reservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
