# Generated by Django 5.2.4 on 2025-08-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_alter_reservation_options_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Chambre individuelle'), ('double', 'Chambre double'), ('triple', 'Chambre triple')], max_length=10, unique=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Loyer mensuel par personne (en DT)', max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, help_text='Montant de la caution par personne (en DT)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Tarification des chambres',
                'verbose_name_plural': 'Tarifications des chambres',
            },
        ),
    ]
