# Generated by Django 5.2.4 on 2025-08-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_roompricing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paid_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof',
            field=models.ImageField(upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de vérification'), ('verified', 'Payé'), ('rejected', 'Rejeté')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='roommate_preference',
            field=models.TextField(blank=True, help_text='Préférence de colocataire (étudiant, travailleur, ou nom connu)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='roompricing',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roompricing',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
